name: coinsnap
description: A new Flutter project.

publish_to: 'none'

version: 1.0.31+32

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.22.5

dependencies:
  flutter:
    sdk: flutter
  localstorage: ^3.0.6
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  http: ^0.12.1
  shared_preferences: '>=0.5.12+4 <2.0.0'
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0
  firebase_analytics: ^7.0.1
  # cloud_firestore: ^0.16.0
  # number_display: ^2.3.0
  cupertino_icons: ^1.0.0
  crypto: ^2.1.5
  equatable: ^1.2.5
  meta: ^1.2.4
  crypto_font_icons: ^0.1.0+1
  typicons_flutter: ^0.2.1
  path_provider: ^1.5.1
  data_connection_checker: ^0.3.4
  local_auth: ^0.6.3+4
  syncfusion_flutter_charts: ^18.4.42
  syncfusion_flutter_sliders: ^18.4.42-beta
  syncfusion_flutter_core: ^18.4.42
  menu_button: ^1.2.1
  autocomplete_textfield: ^1.7.3
  provider: ^4.3.3
  flutter_secure_storage: ^3.3.5
  google_fonts: ^1.1.2
  # smooth_page_indicator: ^0.2.0
  # intro_slider: ^2.3.4
  carousel_slider: ^3.0.0
  dotted_line: ^2.0.2
  intl: ^0.16.1
  search_widget: ^1.0.2
  flutter_keyboard_visibility: any
  smooth_page_indicator: ^0.2.1
  flutter_phoenix: ^0.1.0
  mockito: ^4.1.3
  build_runner: ^1.11.0
  bloc_test: ^7.0.0
  qr_code_scanner: ^0.3.5
  flutter_svg: ^0.19.0
  dotted_border: ^1.0.7
  marquee: ^1.7.0
  cached_network_image: ^2.5.1
  firebase_crashlytics: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets: 
    - graphics/assets/
    - graphics/assets/svg/
    - assets/snapshot_dummydata.json
    - assets/missing_coin_map.json
  uses-material-design: true
  # assets:
  # - graphics/icons/crypto/bitcoin_white_2.png
  fonts:
  - family: Bahnschrift Static
    fonts:
    - asset: fonts/BahnschriftStatic-Regular.ttf
      weight: 400
    - asset: fonts/BahnschriftStatic-Light.ttf
      weight: 200
    - asset: fonts/BahnschriftStatic-SemiLight.ttf
      weight: 300
    - asset: fonts/BahnschriftStatic-SemiBold.ttf
      weight: 500
    - asset: fonts/BahnschriftStatic-Bold.ttf
      weight: 600

    
    # used to test font loading
  - family: Forestion
    fonts:
    - asset: fonts/Forestion.ttf
  - family:  IconCustom
    fonts:
    - asset: fonts/IconCustom.ttf