name: coinsnap
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  http: ^0.12.1
  shared_preferences: '>=0.5.12+4 <2.0.0'
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  # number_display: ^2.3.0
  cupertino_icons: ^1.0.0
  crypto: ^2.1.5
  equatable: ^1.2.5
  meta: ^1.2.4
  crypto_font_icons: ^0.1.0+1
  typicons_flutter: ^0.2.1
  charts_flutter: ^0.9.0
  path_provider: ^1.5.1
  hive: ^1.0.0
  hive_flutter: ^0.2.1

dev_dependencies:
  hive_generator: ^0.5.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - graphics/icons/crypto/bitcoin_white_2.png